{
 "title": "Ampere BMC Sensor Monitor",
 "description": "Collects and displays  information about voltage, current, power, status, temperature on Ampere BMC",
 "tags": [
  "Ampere",
  "bmc",
  "eMag",
  "eMag2"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "bmcip",
    "label": "BMCIP:",
    "query": "label_values(ipmi_sensor, server)"
   }
  ]
 },
 "panels": [
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "content": "# Dashboard Ampere BMC Dashboard\n\n\n\n## Developed by:\n\nRichard Liu "
  },
  {
   "title": "Battery Temperature",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 6, "w": 4, "x": 11, "y": 0 },
   "format": "watt",
   "targets": [
    {
     "application": { "filter": "Battery" },
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"total_power\"}",
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "upsBatteryTemperature" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Power Status",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"total_power\"}",
     "legendFormat": "total_power"
    }
   ]
  },
  { "title": "Voltage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU Voltage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"0v6_ddr0123_vtt\"}",
     "legendFormat": "0v6_ddr0123_vtt"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"0v6_ddr4567_vtt\"}",
     "legendFormat": "0v6_ddr0123_vtt"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"1v2_vddq0123\"}",
     "legendFormat": "1v2_vddq0123"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"1v2_vddq4567\"}",
     "legendFormat": "1v2_vddq4567"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"cpu_vcore\"}",
     "legendFormat": "cpu_vcore"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"0v9_cpu_pcp\"}",
     "legendFormat": "0v9_cpu_pcp"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"0v9_cpu_soc\"}",
     "legendFormat": "0v9_cpu_soc"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"1v5_cpu\"}",
     "legendFormat": "1v5_cpu"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"1v8_cpu_pcp\"}",
     "legendFormat": "1v8_cpu_pcp"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"1v8_cpu_soc\"}",
     "legendFormat": "1v8_cpu_soc"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"3v3_cpu\"}",
     "legendFormat": "3v3_cpu"
    }
   ]
  },
  {
   "title": "PSU Input Voltage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"psu1_vin\"}",
     "legendFormat": "psu1_vin"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"psu2_vin\"}",
     "legendFormat": "psu2_vin"
    }
   ]
  },
  {
   "title": "DDR Voltage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"0v6_ddr0123_vtt\"}",
     "legendFormat": "0v6_ddr0123_vtt"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"0v6_ddr4567_vtt\"}",
     "legendFormat": "0v6_ddr0123_vtt"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"1v2_vddq0123\"}",
     "legendFormat": "1v2_vddq0123"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"1v2_vddq4567\"}",
     "legendFormat": "1v2_vddq4567"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"dimm_ddr_vdd\"}",
     "legendFormat": "dimm_ddr_vdd"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"dimm_vr1_volt\"}",
     "legendFormat": "dimm_vr1_volt"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"dimm_vr2_volt\"}",
     "legendFormat": "dimm_vr2_volt"
    }
   ]
  },
  {
   "title": "MISC Voltage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"2v5\"}",
     "legendFormat": "2v5"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"3v3\"}",
     "legendFormat": "3v3"
    }
   ]
  },
  {
   "title": "BMC Voltage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"3v3_bmc\"}",
     "legendFormat": "3v3_bmc"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"5v_bmc\"}",
     "legendFormat": "5v_bmc"
    }
   ]
  },
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "CPU Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"cpu_diode_temp\"}",
     "legendFormat": "cpu_diode_temp"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"cpu_temp\"}",
     "legendFormat": "cpu_temp"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"soc_vrd_temp\"}",
     "legendFormat": "soc_vrd_temp"
    }
   ]
  },
  {
   "title": "Case Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"in_left_temp\"}",
     "legendFormat": "in_left_temp"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"in_middle_temp\"}",
     "legendFormat": "in_middle_temp"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"in_right_temp\"}",
     "legendFormat": "in_right_temp"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"in_riser_left\"}",
     "legendFormat": "in_riser_left"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"in_riser_right\"}",
     "legendFormat": "in_riser_right"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"out_riser_left\"}",
     "legendFormat": "out_riser_left"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"out_riser_right\"}",
     "legendFormat": "out_riser_right"
    }
   ]
  },
  {
   "title": "MISC Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"pmd_vrd_temp\"}",
     "legendFormat": "pmd_vrd_temp"
    }
   ]
  },
  {
   "title": "Memory Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"dimm_vrd_temp\"}",
     "legendFormat": "dimm_vrd_temp"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\", name=\"dimmg0_temp\"}",
     "legendFormat": "dimmg0_temp"
    }
   ]
  },
  {
   "title": "Room Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "multifile_temperature", "legendFormat": "Temperature" }
   ]
  },
  {
   "title": "Room Humidity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    { "expr": "multifile_humidityrelative", "legendFormat": "Humidity" }
   ]
  },
  { "title": "Power Consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Current Power Consumption",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"cpu_power\"}",
     "legendFormat": "CPU Power"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"dimm_vr1_power\"}\n",
     "legendFormat": "DIMM 1 Power"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"dimm_vr2_power\"}\n",
     "legendFormat": "DIMM 2 Power"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"mem_power\"}\n",
     "legendFormat": "Memory Power"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"total_power\"}\n",
     "legendFormat": "Total Power"
    }
   ]
  },
  {
   "title": "PSU Power Consumption",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"psu1_pout\"}",
     "legendFormat": "psu1_pout"
    },
    {
     "expr": "ipmi_sensor{server=\"$bmcip\",name=\"psu2_pout\"}",
     "legendFormat": "psu2_pout"
    }
   ]
  },
  {
   "title": "FAN Speed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fan Speed",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "rpm" }
     ],
     "targets": [
      {
       "expr": "ipmi_sensor{server=\"$bmcip\", name=\"sys_fan1_speed\"}",
       "legendFormat": "System FAN 1"
      },
      {
       "expr": "ipmi_sensor{server=\"$bmcip\", name=\"sys_fan2_speed\"}",
       "legendFormat": "System FAN 2"
      },
      {
       "expr": "ipmi_sensor{server=\"$bmcip\", name=\"sys_fan3_speed\"}",
       "legendFormat": "System FAN 3"
      },
      {
       "expr": "ipmi_sensor{server=\"$bmcip\", name=\"sys_fan4_speed\"}",
       "legendFormat": "System FAN 4"
      },
      {
       "expr": "ipmi_sensor{server=\"$bmcip\", name=\"sys_fan5_speed\"}",
       "legendFormat": "System FAN 5"
      },
      {
       "expr": "ipmi_sensor{server=\"$bmcip\", name=\"sys_fan6_speed\"}",
       "legendFormat": "System FAN 6"
      },
      {
       "expr": "ipmi_sensor{server=\"$bmcip\", name=\"sys_fan7_speed\"}",
       "legendFormat": "System FAN 7"
      },
      {
       "expr": "ipmi_sensor{server=\"$bmcip\", name=\"sys_fan8_speed\"}",
       "legendFormat": "System FAN 8"
      }
     ]
    },
    {
     "title": "Fan Speed",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "rpm" }
     ],
     "targets": [
      {
       "expr": "ipmi_sensor{server=\"$bmcip\", name=\"psu1_fan_speed\"}",
       "legendFormat": "psu1_fan_speed"
      },
      {
       "expr": "ipmi_sensor{server=\"$bmcip\", name=\"psu2_fan_speed\"}",
       "legendFormat": "psu2_fan_speed"
      }
     ]
    }
   ]
  }
 ]
}