FROM arm64v8/ubuntu:18.04
# RUN sed -i -- 's/# deb-src/deb-src/g' /etc/apt/sources.list
# RUN echo "Acquire::http::Proxy \"http://192.168.110.254:3142\";" >> /etc/apt/apt.conf

RUN apt-get update && apt-get install -y openssh-server apt-utils
RUN mkdir -p /var/run/sshd

RUN export DEBIAN_FRONTEND=noninteractive
RUN apt-get install -y tzdata
RUN ln -fs /usr/share/zoneinfo/Asia/Taiwan /etc/localtime
RUN dpkg-reconfigure --frontend noninteractive tzdata
RUN apt -y install vim tmux lftp net-tools ethtool bc sudo wget
RUN apt -y upgrade
RUN apt autoclean

# Download Telegraf
RUN mkdir -p /work/output
RUN echo "0" > /work/output/in_temp_input
RUN echo "0" > /work/output/in_humidityrelative_input
WORKDIR "/work"
RUN wget https://dl.influxdata.com/telegraf/releases/telegraf_1.13.3-1_arm64.deb
RUN dpkg -i telegraf_1.13.3-1_arm64.deb
RUN apt install -y ipmitool
ADD telegraf.conf /etc/telegraf/telegraf.conf

# Download Prometheus 
RUN wget https://github.com/prometheus/prometheus/releases/download/v2.15.2/prometheus-2.15.2.linux-arm64.tar.gz
RUN tar xvf prometheus-2.15.2.linux-arm64.tar.gz
ADD prometheus.yml /work/prometheus-2.15.2.linux-arm64/prometheus.yml

# Download 
RUN sudo apt-get install -y adduser libfontconfig1
RUN wget https://dl.grafana.com/oss/release/grafana_6.6.0_arm64.deb
RUN dpkg -i grafana_6.6.0_arm64.deb

RUN echo 'root:root' |chpasswd # echo password | passwd --stdin root
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -i '/pam_loginuid.so/c session    optional     pam_loginuid.so'  /etc/pam.d/sshd
RUN echo "export VISIBLE=now" >> /etc/profile
RUN sed -i "s/UsePAM yes/UsePAM no/" /etc/ssh/sshd_config

ADD service.sh /root/service.sh

EXPOSE 22
CMD bash /root/service.sh; /usr/sbin/sshd -D
# CMD bash /root/service.sh;
